// Publish only reviewed public catalog data; never reads/writes a database.
const fs = require('node:fs'), path = require('node:path'), crypto = require('node:crypto')
const root = path.join(__dirname, '..')
const version = process.argv[2], publishedAt = process.argv[3]
if (!/^\d{4}\.\d{2}\.\d{2}\.\d+$/.test(version || '') || !Number.isFinite(Date.parse(publishedAt))) throw Error('Usage: node tools/build_aw_catalog_release.js YYYY.MM.DD.N ISO_TIMESTAMP')
const catalog = require('../miniprogram/data/aw/catalog')
const payload = JSON.stringify({ catalog, ammoEvidence: require('../miniprogram/data/aw/ammo-classification'), presentation: require('../miniprogram/data/aw/presentation') })
const sha256 = crypto.createHash('sha256').update(payload).digest('hex')
const parts = version.split('.')
const sequence = Number(parts.slice(0,3).join('')) * 10000 + Number(parts[3])
const manifest = {schemaVersion:1,version:'aw-'+version+'-'+sha256.slice(0,12),sequence,publishedAt,sourceCheckedAt:catalog.checkedAt,sha256,counts:Object.fromEntries(Object.entries(catalog.tables).map(([k,t])=>[k,t.rows.length]))}
const dir = path.join(root,'supabase/functions/aw-catalog')
fs.mkdirSync(dir,{recursive:true})
fs.writeFileSync(path.join(dir,'release.json'),JSON.stringify({manifest,payload})+'\n')
fs.writeFileSync(path.join(root,'miniprogram/data/aw/release.js'),'// Generated by tools/build_aw_catalog_release.js\nmodule.exports = '+JSON.stringify(manifest)+'\n')
console.log(JSON.stringify({version:manifest.version,bytes:Buffer.byteLength(payload),sha256}))
