// Publish reviewed public data from explicit full baselines; no database access.
const path = require('node:path'), fs = require('node:fs')
const pkg = require('./aw_catalog_package'), {args,required} = require('./build_aw_catalog_package')
const root = path.join(__dirname,'..'), a = args(process.argv.slice(4))
const version = process.argv[2], publishedAt = process.argv[3]
if ((!a.from && !a['full-only']) || (a.from && a['full-only'])) throw Error('Specify --from <previous formal full.json> or --full-only <reason for initial/schema release>')
const archiveDir = path.resolve(a.archive || path.join(root,'data/aw/releases'))
const out = path.resolve(a.output || path.join(root,'supabase/functions/aw-catalog/release.json'))
const content = {catalog:require('../miniprogram/data/aw/catalog'),ammoEvidence:require('../miniprogram/data/aw/ammo-classification'),presentation:require('../miniprogram/data/aw/presentation')}
const bundle = a.to ? pkg.read(a.to) : pkg.full(content,version,publishedAt)
if(a.to && (bundle.manifest.version.split('-')[1] !== version || bundle.manifest.publishedAt !== publishedAt))throw Error('--to version/timestamp do not match arguments')
const patches = []
if(a.from){
  const from = pkg.read(a.from), delta = pkg.patch(from,bundle)
  patches.push(delta);bundle.manifest.patches = [delta.descriptor]
  pkg.archive(archiveDir,from)
} else {bundle.manifest.patches=[];bundle.manifest.fullOnlyReason=required(a,'full-only')}
// Refuse a competing same/older release before mutating latest or bundled metadata.
if(fs.existsSync(out)) {
  const current = pkg.read(out)
  if(current.manifest.sequence >= bundle.manifest.sequence && current.manifest.version !== bundle.manifest.version)throw Error('Latest sequence would regress or conflict')
}
const fullFile = pkg.archive(archiveDir,bundle)
if(patches.length)pkg.write(path.join(path.dirname(fullFile),'patch.json'),patches[0])
pkg.write(out,{...bundle,patches})
if(!a.output)fs.writeFileSync(path.join(root,'miniprogram/data/aw/release.js'),'// Generated by tools/build_aw_catalog_release.js\nmodule.exports = '+JSON.stringify(bundle.manifest)+'\n')
console.log(JSON.stringify({version:bundle.manifest.version,fullBytes:Buffer.byteLength(bundle.payload),patchBytes:patches[0]?Buffer.byteLength(patches[0].payload):0,sha256:bundle.manifest.sha256,fullFile}))
