// Derive only public catalog structure from the Git contract. No database access.
const fs = require('node:fs'), path = require('node:path')
const root = path.join(__dirname, '..')
const contract = require('../data/aw/schema_data_contract.json')
const names = Object.keys(require('../miniprogram/data/aw/catalog').tables).sort()
const schema = {}
const fields = text => text.split(',').map(x => x.trim())
for (const name of names) {
  const columns = contract.columns.filter(c => c.table === 'public.' + name)
  const spec = { columns: {}, primaryKey: [], unique: [], references: [] }
  for (const c of columns.sort((a,b) => a.column < b.column ? -1 : a.column > b.column ? 1 : 0)) spec.columns[c.column] = { type:c.type, required:c.notnull }
  for (const c of contract.constraints.filter(c => c.table === 'public.' + name)) {
    if (c.type === 'p') spec.primaryKey = fields(c.definition.match(/PRIMARY KEY \(([^)]+)\)/)[1])
    if (c.type === 'u') spec.unique.push(fields(c.definition.match(/UNIQUE \(([^)]+)\)/)[1]))
    if (c.type === 'f') {
      const m = c.definition.match(/FOREIGN KEY \(([^)]+)\) REFERENCES (\w+)\(([^)]+)\)/)
      if (!m || !names.includes(m[2])) throw Error('Unrecognized public catalog reference: ' + c.definition)
      spec.references.push({ fields:fields(m[1]), table:m[2], target:fields(m[3]) })
    }
  }
  if (!spec.primaryKey.length) throw Error('Missing stable key: ' + name)
  schema[name] = spec
}
fs.writeFileSync(path.join(root,'miniprogram/data/aw/schema.js'), '// Generated by tools/build_aw_catalog_schema.js from the public Git contract.\nmodule.exports = ' + JSON.stringify(schema) + '\n')
