// No second protocol implementation: wrap the exact tested CommonJS sources for Deno.
const fs=require('node:fs'),path=require('node:path')
const root=path.resolve(__dirname,'..')
const modules=[['awSchema','miniprogram/data/aw/schema.js'],['awChecksum','miniprogram/utils/aw/checksum.js'],['awProtocol','miniprogram/utils/aw/catalog-package.js']]
let output='// Generated by tools/build_aw_edge_protocol.js. Do not edit.\n'
for(const [id,file] of modules){
  let source=fs.readFileSync(path.join(root,file),'utf8')
  source=source.replace("require('../../data/aw/schema')",'awSchema').replace("require('./checksum')",'awChecksum')
  output+=`/** @type {any} */
const ${id}=(()=>{/** @type {{exports:any}} */const module={exports:{}};\n${source}\nreturn module.exports})()\n`
}
// Publisher's pure full/patch/verify functions are shared too (remove filesystem adapters).
let publisher=fs.readFileSync(path.join(root,'tools/aw_catalog_package.js'),'utf8')
publisher=publisher.slice(publisher.indexOf('function full('),publisher.indexOf('function read('))
output+=`const publisher=(()=>{const p=awProtocol,sha256=awChecksum;\n${publisher}\nreturn {full,patch,verify}})()\nexport {awProtocol as protocol,publisher,awChecksum as checksum}\n`
const target=path.join(root,'supabase/functions/_shared/aw-protocol.mjs')
if(process.argv.includes('--check')){if(fs.readFileSync(target,'utf8')!==output)throw Error('Stale edge protocol; run node tools/build_aw_edge_protocol.js')}
else fs.writeFileSync(target,output)
