// Publish reviewed public data from explicit full baselines; no database access.
const path = require('node:path'), fs = require('node:fs')
const pkg = require('./aw_catalog_package'), {args,required} = require('./build_aw_catalog_package')
const protocol = require('../miniprogram/utils/aw/catalog-package'), {baseline} = require('./aw_catalog_deployment')
const root = path.join(__dirname,'..'), a = args(process.argv.slice(4))
const version = process.argv[2], publishedAt = process.argv[3]
if ((!a.from && !a['full-only']) || (a.from && a['full-only'])) throw Error('Specify --from <previous formal full.json> or --full-only <reason for initial/schema release>')
const archiveDir = path.resolve(a.archive || path.join(root,'data/aw/releases'))
const out = path.resolve(a.output || path.join(root,'supabase/functions/aw-catalog/release.json'))
const content = {catalog:require('../miniprogram/data/aw/catalog'),ammoEvidence:require('../miniprogram/data/aw/ammo-classification'),presentation:require('../miniprogram/data/aw/presentation')}
const bundle = a.to ? pkg.read(a.to) : pkg.full(content,version,publishedAt)
if(a.to && (bundle.manifest.version.split('-')[1] !== version || bundle.manifest.publishedAt !== publishedAt))throw Error('--to version/timestamp do not match arguments')
protocol.validate(bundle)
if(!a.output && !a['no-bundled'] && bundle.payload !== protocol.canonicalPayload(content))throw Error('Target full differs from bundled source modules; rebuild them or explicitly use --no-bundled <data-only release reason>')
const patches = []
let from
if(a.from){
  from = pkg.read(a.from)
  protocol.validate(from)
  if(!a.draft)baseline(path.resolve(a.deployed || path.join(root,'data/aw/deployed.json')),required(a,'environment'),from,root)
  const delta = pkg.patch(from,bundle)
  patches.push(delta);bundle.manifest.patches = [delta.descriptor]
} else {bundle.manifest.patches=[];bundle.manifest.fullOnlyReason=required(a,'full-only')}
// Refuse a competing same/older release before mutating latest or bundled metadata.
if(fs.existsSync(out)) {
  const current = pkg.read(out)
  if(current.manifest.sequence >= bundle.manifest.sequence && current.manifest.version !== bundle.manifest.version)throw Error('Latest sequence would regress or conflict')
}
// All baseline/target/latest checks precede writes, including immutable archives.
for(const candidate of [from,bundle].filter(Boolean)) {
  const file=path.join(archiveDir,candidate.manifest.version,'full.json')
  if(fs.existsSync(file) && protocol.stringify(pkg.read(file)) !== protocol.stringify({manifest:candidate.manifest,payload:candidate.payload}))throw Error('Immutable release archive already differs: '+file)
}
if(from)pkg.archive(archiveDir,from)
const fullFile = pkg.archive(archiveDir,bundle)
if(patches.length)pkg.write(path.join(path.dirname(fullFile),'patch.json'),patches[0])
pkg.write(out,{...bundle,patches})
if(!a.output && !a['no-bundled'])fs.writeFileSync(path.join(root,'miniprogram/data/aw/release.js'),'// Generated by tools/build_aw_catalog_release.js\nmodule.exports = '+JSON.stringify(bundle.manifest)+'\n')
console.log(JSON.stringify({version:bundle.manifest.version,fullBytes:Buffer.byteLength(bundle.payload),patchBytes:patches[0]?Buffer.byteLength(patches[0].payload):0,sha256:bundle.manifest.sha256,fullFile,draftReason:a.draft||null,bundledSynced:!a.output&&!a['no-bundled']}))
